#
# Makefile for libdistorm3
#

obj-y				+= decoder.o
obj-y				+= distorm.o
obj-y				+= instructions.o
obj-y				+= insts.o
obj-y				+= mnemonics.o
obj-y				+= operands.o
obj-y				+= prefix.o
obj-y				+= textdefs.o
obj-y				+= wstring.o
